spring:
  application:
    name: wcg
  datasource:
    url: jdbc:h2:file:./bazaDanych
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  error:
    include-stacktrace: never
logging.level.org.hibernate.type: trace
